-- MySQL Script generated by MySQL Workbench
-- 11/17/16 11:28:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema web3project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `web3project` ;

-- -----------------------------------------------------
-- Schema web3project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web3project` DEFAULT CHARACTER SET utf8 ;
USE `web3project` ;

-- -----------------------------------------------------
-- Table `web3project`.`Artist_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`Artist_category` ;

CREATE TABLE IF NOT EXISTS `web3project`.`Artist_category` (
  `ac_code` INT NOT NULL,
  `ac_Name` VARCHAR(45) NULL,
  `ac_description` VARCHAR(225) NULL,
  PRIMARY KEY (`ac_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`Artists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`Artists` ;

CREATE TABLE IF NOT EXISTS `web3project`.`Artists` (
  `artist_id` INT NOT NULL AUTO_INCREMENT,
  `Artist_category_ac_code` INT NOT NULL,
  `F_name` VARCHAR(45) NOT NULL,
  `L_Name` VARCHAR(45) NOT NULL,
  `A_gender` VARCHAR(45) NULL,
  `pic_filename` BLOB NULL,
  `artist_desc` VARCHAR(225) NULL,
  PRIMARY KEY (`artist_id`),
  INDEX `fk_Artists_Artist_category_idx` (`Artist_category_ac_code` ASC),
  CONSTRAINT `fk_Artists_Artist_category`
    FOREIGN KEY (`Artist_category_ac_code`)
    REFERENCES `web3project`.`Artist_category` (`ac_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`Artist_News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`Artist_News` ;

CREATE TABLE IF NOT EXISTS `web3project`.`Artist_News` (
  `newsID` INT NOT NULL AUTO_INCREMENT,
  `Artists_artist_id` INT NOT NULL,
  `PublishDate` DATETIME NULL,
  `newsText` VARCHAR(225) NULL,
  `newsURL` VARCHAR(225) NULL,
  PRIMARY KEY (`newsID`),
  INDEX `fk_Artist_News_Artists1_idx` (`Artists_artist_id` ASC),
  CONSTRAINT `fk_Artist_News_Artists1`
    FOREIGN KEY (`Artists_artist_id`)
    REFERENCES `web3project`.`Artists` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`address` ;

CREATE TABLE IF NOT EXISTS `web3project`.`address` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `county` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `postalCode` VARCHAR(45) NULL,
  PRIMARY KEY (`addressID`))
ENGINE = InnoDB
COMMENT = '`			';


-- -----------------------------------------------------
-- Table `web3project`.`Venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`Venue` ;

CREATE TABLE IF NOT EXISTS `web3project`.`Venue` (
  `venueID` INT NOT NULL AUTO_INCREMENT,
  `address_addressID` INT NOT NULL,
  `vName` VARCHAR(45) NULL,
  `vSeatCap` INT NULL,
  PRIMARY KEY (`venueID`),
  INDEX `fk_Venue_address1_idx` (`address_addressID` ASC),
  CONSTRAINT `fk_Venue_address1`
    FOREIGN KEY (`address_addressID`)
    REFERENCES `web3project`.`address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`RefEventCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`RefEventCategory` ;

CREATE TABLE IF NOT EXISTS `web3project`.`RefEventCategory` (
  `eventCategoryCode` INT NOT NULL AUTO_INCREMENT,
  `ecDescription` VARCHAR(225) NULL,
  PRIMARY KEY (`eventCategoryCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`Events` ;

CREATE TABLE IF NOT EXISTS `web3project`.`Events` (
  `eventID` INT NOT NULL AUTO_INCREMENT,
  `Artists_artist_id` INT NOT NULL,
  `RefEventCategory_eventCategoryCode` INT NOT NULL,
  `Venue_venueID` INT NOT NULL,
  `eventName` VARCHAR(45) NOT NULL,
  `event_Sdate` DATETIME NOT NULL,
  `event_Fdate` DATETIME NULL,
  `Ticket_Sdate` DATETIME NULL,
  `ticketPrice` VARCHAR(45) NULL,
  PRIMARY KEY (`eventID`),
  INDEX `fk_Events_Artists1_idx` (`Artists_artist_id` ASC),
  INDEX `fk_Events_Venue1_idx` (`Venue_venueID` ASC),
  INDEX `fk_Events_RefEventCategory1_idx` (`RefEventCategory_eventCategoryCode` ASC),
  CONSTRAINT `fk_Events_Artists1`
    FOREIGN KEY (`Artists_artist_id`)
    REFERENCES `web3project`.`Artists` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_Venue1`
    FOREIGN KEY (`Venue_venueID`)
    REFERENCES `web3project`.`Venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_RefEventCategory1`
    FOREIGN KEY (`RefEventCategory_eventCategoryCode`)
    REFERENCES `web3project`.`RefEventCategory` (`eventCategoryCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`VenueDirections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`VenueDirections` ;

CREATE TABLE IF NOT EXISTS `web3project`.`VenueDirections` (
  `VenueDirectionsID` INT NOT NULL AUTO_INCREMENT,
  `Instructions` VARCHAR(45) NULL,
  `Venue_venueID` INT NOT NULL,
  PRIMARY KEY (`VenueDirectionsID`),
  INDEX `fk_VenueDirections_Venue1_idx` (`Venue_venueID` ASC),
  CONSTRAINT `fk_VenueDirections_Venue1`
    FOREIGN KEY (`Venue_venueID`)
    REFERENCES `web3project`.`Venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`VenueRows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`VenueRows` ;

CREATE TABLE IF NOT EXISTS `web3project`.`VenueRows` (
  `RowsID` INT NOT NULL AUTO_INCREMENT,
  `rowSeat` VARCHAR(45) NULL,
  `Venue_venueID` INT NOT NULL,
  PRIMARY KEY (`RowsID`, `Venue_venueID`),
  INDEX `fk_VenueRows_Venue1_idx` (`Venue_venueID` ASC),
  CONSTRAINT `fk_VenueRows_Venue1`
    FOREIGN KEY (`Venue_venueID`)
    REFERENCES `web3project`.`Venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`Members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`Members` ;

CREATE TABLE IF NOT EXISTS `web3project`.`Members` (
  `membersID` INT NOT NULL AUTO_INCREMENT,
  `address_addressID` INT NOT NULL,
  `mFName` VARCHAR(45) NOT NULL,
  `mLName` VARCHAR(45) NOT NULL,
  `mGender` VARCHAR(11) NULL,
  `mEmail` VARCHAR(90) NULL,
  `mPassword` VARCHAR(45) NOT NULL,
  `ccType` VARCHAR(45) NOT NULL,
  `ccNumber` VARCHAR(45) NOT NULL,
  `ccDate` DATE NOT NULL,
  `CCccv` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`membersID`),
  INDEX `fk_Members_address1_idx` (`address_addressID` ASC),
  CONSTRAINT `fk_Members_address1`
    FOREIGN KEY (`address_addressID`)
    REFERENCES `web3project`.`address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`MemberOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`MemberOrders` ;

CREATE TABLE IF NOT EXISTS `web3project`.`MemberOrders` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `Members_membersID` INT NOT NULL,
  `Events_eventID` INT NOT NULL,
  `orderDate` DATETIME NOT NULL,
  `orderStatus` VARCHAR(45) NOT NULL,
  `orderCardNumber` VARCHAR(45) NOT NULL,
  `orderPhoneNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_MemberOrders_Events1_idx` (`Events_eventID` ASC),
  INDEX `fk_MemberOrders_Members1_idx` (`Members_membersID` ASC),
  CONSTRAINT `fk_MemberOrders_Events1`
    FOREIGN KEY (`Events_eventID`)
    REFERENCES `web3project`.`Events` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MemberOrders_Members1`
    FOREIGN KEY (`Members_membersID`)
    REFERENCES `web3project`.`Members` (`membersID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web3project`.`seatReservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web3project`.`seatReservation` ;

CREATE TABLE IF NOT EXISTS `web3project`.`seatReservation` (
  `seatID` INT NOT NULL AUTO_INCREMENT,
  `Members_membersID` INT NOT NULL,
  `VenueRows_RowsID` INT NOT NULL,
  `VenueRows_Venue_venueID` INT NOT NULL,
  `seatnumber` VARCHAR(4) NULL,
  PRIMARY KEY (`seatID`),
  INDEX `fk_seatReservation_Members1_idx` (`Members_membersID` ASC),
  INDEX `fk_seatReservation_VenueRows1_idx` (`VenueRows_RowsID` ASC, `VenueRows_Venue_venueID` ASC),
  CONSTRAINT `fk_seatReservation_Members1`
    FOREIGN KEY (`Members_membersID`)
    REFERENCES `web3project`.`Members` (`membersID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seatReservation_VenueRows1`
    FOREIGN KEY (`VenueRows_RowsID` , `VenueRows_Venue_venueID`)
    REFERENCES `web3project`.`VenueRows` (`RowsID` , `Venue_venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
